### PR TITLE
fix(grid view): make preview settings consistent with preview image size (DSP-1548)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves DSP-1548

The preview image has the the dimensions 128x128 (max) as defined in the preview image IIIF URL: https://github.com/dasch-swiss/dsp-api/blob/7497023c3cc117d08c3d5eaae807ac53451dae64/webapi/src/main/scala/org/knora/webapi/messages/util/ValueUtilV1.scala#L100

### CODE REVIEW

**Review by gautschr — APPROVED** [review]
works perfectly - thank you!

**Review by subotic — APPROVED** [review]
👍

**Comment by tobiasschweizer** [comment]
@subotic The same settings are used in `tableedit.js`:

https://github.com/dasch-swiss/dsp-tangoh-app/blob/c3f4609390bc1a20eda7eec1e9136705f5b894e5/app/public/js/jquery.tableedit.js#L133

Do these have to adapted as well?

**Comment by tobiasschweizer** [comment]
Also the grid throws an error if a resource has to `preview_path`.

**Pull request merged**
