### PR TITLE
fix(window controls): keep ctrl buttons visible (DSP-1384)

### PR DESCRIPTION
**Pull request by loicjaouen**
resolves DSP-1384

~~it is still a work in progress~~
it is ready for review

### CODE REVIEW

**Comment by loicjaouen** [comment]
initial state:
tangoh-missing-controls

**Comment by loicjaouen** [comment]
with buttons:
Screenshot_2021-02-25 System for Annotation and Linkage of Sources in Arts and Humanities(5)

**Comment by loicjaouen** [comment]
Screenshot_2021-02-25 System for Annotation and Linkage of Sources in Arts and Humanities(6)

**Comment by loicjaouen** [comment]
apparently lesscss is broken and css files are edited directly

**Comment by loicjaouen** [comment]
Screenshot_2021-02-25 System for Annotation and Linkage of Sources in Arts and Humanities(7)

**Comment by loicjaouen** [comment]
the above commit makes long title to behave nicely to their shorter pairs:
Screenshot_2021-02-25 System for Annotation and Linkage of Sources in Arts and Humanities(8)

**Review by subotic — APPROVED** [review]
cool, thanks :-)

**Pull request merged**
