### PR TITLE
fix(geoname): add missing logic for Geoname values (DSP-1373)

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-1373, DSP-1486

requires https://github.com/dasch-swiss/dsp-api/commit/9d0e93e96891660e4484f9b23683aa9aefb18938

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@subotic: I could make the Geoname value work again without the "old" backend logic. However, this means that the GUI performs more requests to the Geonames API. Is this a problem (licensing)`

**Comment by subotic** [comment]
Great 👍 No idea, we will see.

**Comment by tobiasschweizer** [comment]
Still got a CSS problem with the autocomplete:

Screenshot 2021-04-06 at 08 36 43

**Comment by tobiasschweizer** [comment]
@subotic I have the suspicion that `jquery-ui.css` is missing in dsp-tangoh-app. Could you help me add it with bazel?

**Comment by tobiasschweizer** [comment]
there are some missing images that are referenced as background images in CSS, e.g.,  "ui-bg_highlight-soft_100_eeeeee_1x100.png". But I think they are missing in the old SALSAH, too. @kilchenmann @lrosenth Do you know more about that?

**Comment by kilchenmann** [comment]
> there are some missing images that are referenced as background images in CSS, e.g., "ui-bg_highlight-soft_100_eeeeee_1x100.png". But I think they are missing in the old SALSAH, too. @kilchenmann @lrosenth Do you know more about that?

I don't know about this image. But I figured out that it's part of selenium. (does it make any sense?)

**Comment by tobiasschweizer** [comment]
> > there are some missing images that are referenced as background images in CSS, e.g., "ui-bg_highlight-soft_100_eeeeee_1x100.png". But I think they are missing in the old SALSAH, too. @kilchenmann @lrosenth Do you know more about that?
> 
> I don't know about this image. But I figured out that it's part of selenium. (does it make any sense?)

So maybe it would make sense to remove them from CSS? 

https://github.com/dasch-swiss/dsp-tangoh-app/blob/cb0788408d0c1cc635f030da2a8b877448682b74/app/public/less/jquery-ui.css#L848

**Comment by tobiasschweizer** [comment]
@kilchenmann @lrosenth I have a question about this condition

https://github.com/dasch-swiss/dsp-tangoh-app/blob/cb0788408d0c1cc635f030da2a8b877448682b74/app/public/js/jquery.geonames.js#L239

Since in dsp-tangoh-app the old Salsah's backend logic is not supported, this check does not make sense here. Could it be removed? 

If I understand correctly, its purpose is to prevent making new requests to Geonames API by working with the hierarchical list as is.

**Review by lrosenth — APPROVED** [review]
Looks perfect! Thanks a lot

**Review by lrosenth — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
I remove the logic related to `new_entry_allowed` in https://github.com/dasch-swiss/dsp-tangoh-app/pull/7/commits/77d82f50ea488925c947704a5a4017df4036ad6e

**Pull request merged**
